Repository liferay/eslint-config-liferay, pull requests merged in 2019-08, with the labels that each got.

#56 chore: update to ESLint v6
  package.json
  utils/local.js
  yarn.lock
Labels: chore

#58 feat!: enforce use of React fragment shorthand syntax
  react.js
Labels: feature

#60 doc: remove unnecessary blank line from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#62 feat: adds no-global-fetch rule to avoid direct usage of fetch in favour of our thin wrapper
  README.md
  plugins/eslint-plugin-liferay-portal/docs/rules/no-global-fetch.md
  plugins/eslint-plugin-liferay-portal/index.js
  plugins/eslint-plugin-liferay-portal/lib/rules/no-global-fetch.js
  plugins/eslint-plugin-liferay-portal/tests/lib/rules/no-global-fetch.js
  portal.js
Labels: feature

#66 feat!: activate the "radix" rule
  index.js
Labels: feature

#68 docs: provide links to justify rule choices
  README.md
Labels: documentation

#73 feat: configure Semantic Pull Requests bot
  .github/semantic.yml
Labels: feature

#71 feat: add liferay-portal/no-react-dom-render rule
  README.md
  plugins/eslint-plugin-liferay-portal/docs/rules/no-react-dom-render.md
  plugins/eslint-plugin-liferay-portal/index.js
  plugins/eslint-plugin-liferay-portal/lib/rules/no-react-dom-render.js
  plugins/eslint-plugin-liferay-portal/tests/lib/rules/no-react-dom-render.js
  portal.js
Labels: feature

#76 docs: flesh out the no-react-dom-render docs
  plugins/eslint-plugin-liferay-portal/docs/rules/no-react-dom-render.md
Labels: documentation

#75 feat: add padded-test-blocks
  README.md
  index.js
  plugins/eslint-plugin-liferay/index.js
  plugins/eslint-plugin-liferay/lib/rules/padded-test-blocks.js
  plugins/eslint-plugin-liferay/tests/lib/rules/padded-test-blocks.js
Labels: feature

#78 fix: always resolve "eslint" relative to $PWD
  utils/local.js
Labels: bug

#79 feat!: activate "no-console" rule
  README.md
  index.js
Labels: feature
